name: Build Windows

on:
  push:
    branches: master
  workflow_dispatch: {}

jobs:
  build:
    name: Run build steps
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v3
        id: buildStep
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          buildName: hatbor
          versioning: Semantic

      # Output
      - uses: actions/upload-artifact@v3
        with:
          name: 'hatbor-${{ steps.buildStep.with.targetPlatform }}-${{ steps.buildStep.outputs.buildVersion }}'
          path: build
