name: Build Windows

on:
  push:
    branches: master
  workflow_dispatch: {}

jobs:
  build:
    name: Build for StandaloneWindows64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Build project
        uses: game-ci/unity-builder@v4
        id: buildStep
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          buildName: hatbor
          versioning: Semantic

      - uses: actions/upload-artifact@v3
        with:
          name: hatbor-Windows-${{ steps.buildStep.outputs.buildVersion }}
          path: build/StandaloneWindows64

      - name: Upload to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DIR: ${{ format('{0}/build/StandaloneWindows64', github.workspace) }}
          ZIP: ${{ format('hatbor-Windows-{0}.zip', steps.buildStep.outputs.buildVersion) }}
          CONTENT: ${{ format('hatbor {0} for Windows', steps.buildStep.outputs.buildVersion) }}
        run: |
          zip -qq -r $ZIP $DIR
          curl \
            -F 'payload_json={"content":"$CONTENT"}' \
            -F "file1=@$ZIP" \
            $DISCORD_WEBHOOK
